version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ] # Test connection with a simple command
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  database:
    image: postgres:17.1
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  app-create-video-request:
    image: earthtvapp:latest
    restart: always
    command: python source/video/create_video_request.py
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
  app-service-videos:
    image: earthtvapp:latest
    restart: always
    command: python source/services/service_videos.py
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
  app-create-frame-request:
    image: earthtvapp:latest
    restart: always
    command: python source/frame/create_frame_request.py
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
  app-service-frames:
    image: earthtvapp:latest
    restart: always
    command: python source/services/service_frames.py
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
  app-create-frame-image:
    image: earthtvapp:latest
    restart: always
    command: python source/frame/create_frame_image.py
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
  app-create-video:
    image: earthtvapp:latest
    restart: always
    command: python source/video/create_video.py
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    volumes:
      - ./output:/app/output
volumes:
  cache:
    driver: local
  database:
    driver: local
